# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fac_Desc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SystemName', models.CharField(max_length=20, verbose_name='\u7cfb\u7edf\u540d\u79f0')),
                ('HostName', models.CharField(max_length=20, null=True, verbose_name='\u4e3b\u673a\u540d')),
                ('IpAddress', models.GenericIPAddressField(verbose_name='IP\u5730\u5740')),
                ('ServerAdminUser', models.CharField(max_length=20, verbose_name='\u7cfb\u7edf\u7ba1\u7406\u5458\u7528\u6237\u540d')),
                ('ServerAdminPassword', models.CharField(max_length=50, verbose_name='\u7cfb\u7edf\u7ba1\u7406\u5458\u5bc6\u7801')),
                ('onLineDate', models.DateField(verbose_name='\u4e0a\u7ebf\u65e5\u671f')),
                ('belongTo', models.CharField(max_length=10, verbose_name='\u8d1f\u8d23\u4eba')),
                ('createDate', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('updateDate', models.DateField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u671f')),
                ('BuyFrom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sysadmin.Factory', verbose_name='\u8d2d\u4e70\u5382\u5546')),
            ],
        ),
        migrations.CreateModel(
            name='SystemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeId', models.IntegerField(verbose_name='\u7cfb\u7edf\u7c7b\u578b')),
                ('typeDesc', models.CharField(max_length=20, verbose_name='\u7cfb\u7edf\u63cf\u8ff0')),
                ('createDate', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('updateDate', models.DateField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u671f')),
            ],
        ),
        migrations.AddField(
            model_name='system',
            name='sysType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysadmin.SystemType', verbose_name='\u7cfb\u7edf\u7c7b\u578b'),
        ),
    ]
