# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('queryRight', models.IntegerField(default=1)),
                ('editRight', models.IntegerField(default=1)),
                ('updateRight', models.IntegerField(default=1)),
                ('deleteRight', models.IntegerField(default=1)),
                ('createDate', models.DateField(auto_now_add=True)),
                ('updateDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('loginName', models.CharField(max_length=20)),
                ('usercode', models.CharField(max_length=5)),
                ('pwd', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('createDate', models.DateField(auto_now_add=True)),
                ('updateDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='userRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('role_desc', models.CharField(max_length=20)),
                ('role_code', models.CharField(max_length=5)),
                ('createDate', models.DateField(auto_now_add=True)),
                ('updateDate', models.DateField(auto_now=True)),
                ('role_right', models.ManyToManyField(to='app01.Right')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='usrRole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.userRole'),
        ),
    ]
