# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role_code',
            field=models.CharField(max_length=5),
        ),
    ]
