# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetName', models.CharField(max_length=20, verbose_name='\u8d44\u4ea7\u540d\u79f0')),
                ('local', models.CharField(max_length=50)),
                ('Factory', models.CharField(max_length=20, verbose_name='\u5382\u5546')),
                ('UserOrDep', models.CharField(max_length=20, verbose_name='\u4f7f\u7528\u4eba\u6216\u90e8\u95e8')),
                ('createDate', models.DateField(auto_now_add=True)),
                ('updateDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u8d44\u4ea7\u7c7b\u522b\u540d\u79f0')),
            ],
        ),
        migrations.AddField(
            model_name='assetlist',
            name='assetType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asset.AssetType'),
        ),
    ]
