# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.CharField(max_length=10, verbose_name='\u9500\u552e\u4eba\u5458')),
                ('sales_phone', models.CharField(max_length=20, null=True, verbose_name='\u9500\u552e\u7535\u8bdd\u53f7\u7801')),
                ('engineer', models.CharField(max_length=10, null=True, verbose_name='\u6280\u672f\u4eba\u5458')),
                ('engineer_phone', models.CharField(max_length=20, null=True, verbose_name='\u6280\u672f\u4eba\u5458\u7535\u8bdd\u53f7\u7801')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u671f')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Support_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_info', models.CharField(max_length=500, verbose_name='\u7ef4\u62a4\u8bb0\u5f55')),
                ('rec_support_user', models.CharField(max_length=10, verbose_name='\u7ef4\u62a4\u4eba\u5458')),
                ('rec_date', models.DateField(verbose_name='\u7ef4\u62a4\u65f6\u95f4')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierBusinessInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u4f9b\u5e94\u5546\u540d\u79f0')),
                ('bus_info_desc', models.CharField(max_length=50, verbose_name='\u4f9b\u5e94\u5546\u4e1a\u52a1\u63cf\u8ff0')),
                ('bus_info_isCore', models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u6838\u5fc3\u4e1a\u52a1')),
                ('supplier_phone', models.CharField(max_length=20, null=True, verbose_name='\u4f9b\u5e94\u5546\u516c\u53f8\u7535\u8bdd\u53f7\u7801')),
                ('Manager', models.CharField(max_length=10, null=True, verbose_name='\u4f9b\u5e94\u5546\u7ecf\u7406')),
                ('Address', models.CharField(max_length=200, null=True, verbose_name='\u4f9b\u5e94\u5546\u5730\u5740')),
                ('Zip_code', models.CharField(max_length=6, null=True, verbose_name='\u90ae\u653f\u7f16\u7801')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u671f')),
            ],
        ),
        migrations.CreateModel(
            name='SupportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supportType', models.IntegerField(verbose_name='\u652f\u6301\u7c7b\u578b')),
                ('supportDesc', models.CharField(max_length=100, verbose_name='\u652f\u6301\u7c7b\u578b\u63cf\u8ff0')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
            ],
        ),
        migrations.CreateModel(
            name='sysType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_type', models.IntegerField(verbose_name='\u7cfb\u7edf\u7c7b\u578b')),
                ('sysDesc', models.CharField(max_length=200, verbose_name='\u7cfb\u7edf\u7c7b\u578b\u63cf\u8ff0')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
            ],
        ),
        migrations.AddField(
            model_name='supplier_support_record',
            name='Support_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.SupportType'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='Supplier_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.SupplierBusinessInfo', verbose_name='\u4f9b\u5e94\u5546\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='systemType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.sysType', verbose_name='\u7cfb\u7edf\u7c7b\u578b'),
        ),
    ]
